server:
  port: 8001  # Porta padrão para a aplicação

spring:
  application:
    name: nextgenqa  # Nome da aplicação
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration  # Desabilita a configuração automática do DataSource
